import java.util.Scanner;


public class Main

  public static void main (String[] args  
String phrase;    // a string of characters

int countBlank;   // the number of blanks (spaces) in the phrase

 int length;       // the length of the phrase

 char ch;          // an individual character in the string

  int i;

         
  Scanner scan = new Scanner(System.in);


 // Print a program header

 System.out.println ();

 System.out.println ("Character Counter");
 System.out.println ();

 

 // Read in a string and find its length

 System.out.print ("Enter a sentence or phrase: ");

 phrase = scan.nextLine();
 length = phrase.length();

 

// Initialize counts

countBlank = 0;

         
     

// a for loop to go through the string character by character

// and count the blank spaces

for (i = 0; i < length ; i++ )

     System.out.println ();

ch = phrase.charAt(i);


 System.out.println ();

 System.out.println ("Number of blank spaces: " + countBlank);

 System.out.println ();
    }
}
